[package]
name = "sdk-node"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Node.js bindings for my-sdk"

[lints]
workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
sdk-core = { path = "../core", features = ["node"] }
tokio = { version = "1", features = ["rt-multi-thread"] }
napi = { version = "2", features = ["async", "tokio_rt"] }
napi-derive = "2"

[build-dependencies]
napi-build = "2"
