[package]
name = "sdk-python"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Python bindings for Quicknode SDK"

[lib]
name = "_core"
crate-type = ["cdylib"]

[dependencies]
sdk-core = { path = "../core", features = ["python"] }
pyo3 = { workspace = true, features = ["extension-module", "experimental-async"] }
pyo3-async-runtimes = { workspace = true, features = ["tokio-runtime"] }
pyo3-stub-gen = { workspace = true}

