/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Add two numbers */
export declare function add(a: number, b: number): number
/** Divide two numbers */
export declare function divide(a: number, b: number): number
/** Get random UUID with async http request */
export declare function getExternalUuid(): Promise<string>
