/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface GetEndpointsRequest {
  limit?: number
  offset?: number
  tagIds?: Array<number>
  tagLabels?: Array<string>
}
export interface GetEndpointsResponse {
  data: Array<Endpoint>
  error?: string
}
export interface Endpoint {
  id: string
  label?: string
  chain: string
  network: string
  httpUrl: string
  wssUrl?: string
  tags: Array<EndpointTag>
}
export interface EndpointTag {
  tagId: number
  label: string
}
export interface HttpConfig {
  timeoutSecs?: number
  poolMaxIdlePerHost?: number
}
export interface AdminConfig {
  baseUrl?: string
}
export interface SdkFullConfig {
  apiKey: string
  http?: HttpConfig
  admin?: AdminConfig
}
export declare class QuickNodeSdk {
  constructor(config: SdkFullConfig)
  get admin(): AdminApiClient
  static fromEnv(): QuickNodeSdk
}
export declare class AdminApiClient {
  getEndpoints(params?: GetEndpointsRequest | undefined | null): Promise<GetEndpointsResponse>
}
