// Exported main sdk file that imports from autogenerated napi-rs file
//
const _index = require("./index.js");
const { QuicknodeSdk: _QuicknodeSdk } = _index;
const errors = require("./errors.js");

class QuicknodeSdk {
  constructor(config) {
    try {
      this._inner = new _QuicknodeSdk(config);
    } catch (e) {
      throw errors.fromNapiError(e);
    }
    this.admin = errors.wrapClient(this._inner.admin);
    this.streams = errors.wrapClient(this._inner.streams);
    this.webhooks = errors.wrapClient(this._inner.webhooks);
    this.kvstore = errors.wrapClient(this._inner.kvstore);
  }

  static fromEnv() {
    const instance = Object.create(QuicknodeSdk.prototype);
    try {
      instance._inner = _QuicknodeSdk.fromEnv();
    } catch (e) {
      throw errors.fromNapiError(e);
    }
    instance.admin = errors.wrapClient(instance._inner.admin);
    instance.streams = errors.wrapClient(instance._inner.streams);
    instance.webhooks = errors.wrapClient(instance._inner.webhooks);
    instance.kvstore = errors.wrapClient(instance._inner.kvstore);
    return instance;
  }
}

// TemplateArgs wraps the webhook template input with typed static factory
// methods. The underlying object is `{ templateId, args }` — callers should
// use the factory methods rather than constructing the object directly.
class TemplateArgs {
  constructor(templateId, args) {
    this.templateId = templateId;
    this.args = args;
  }

  static evmWalletFilter(attrs) {
    return new TemplateArgs("evmWalletFilter", attrs);
  }

  static evmContractEvents(attrs) {
    return new TemplateArgs("evmContractEvents", attrs);
  }

  static evmAbiFilter(attrs) {
    return new TemplateArgs("evmAbiFilter", attrs);
  }

  static solanaWalletFilter(attrs) {
    return new TemplateArgs("solanaWalletFilter", attrs);
  }

  static bitcoinWalletFilter(attrs) {
    return new TemplateArgs("bitcoinWalletFilter", attrs);
  }

  static xrplWalletFilter(attrs) {
    return new TemplateArgs("xrplWalletFilter", attrs);
  }

  static hyperliquidWalletEventsFilter(attrs) {
    return new TemplateArgs("hyperliquidWalletEventsFilter", attrs);
  }

  static stellarWalletTransactionsFilter(attrs) {
    return new TemplateArgs("stellarWalletTransactionsSourceAccountFilter", attrs);
  }
}

module.exports = {
  ..._index,
  QuicknodeSdk,
  TemplateArgs,
  QuicknodeError: errors.QuicknodeError,
  ConfigError: errors.ConfigError,
  HttpError: errors.HttpError,
  TimeoutError: errors.TimeoutError,
  ConnectionError: errors.ConnectionError,
  ApiError: errors.ApiError,
  DecodeError: errors.DecodeError,
};
